(define (problem zombie_1)
	(:domain zombie)
	(:objects john anne maggie rick bob matt robin
	 forest vilage johnhouse neighborhouse hospital hospitaldoor store vilageislandbridge island islandwest islandeast islandmountainbridge mountain mountainwest mountaineast
	 antidote1 antidote2 antidote3 antidote4 antidote5 wood1 wood2 wood3 wood4 hospitalkey toolkit1 toolkit2 food1 food2 food3 food4 food5
	 zombie
	 bigzombie
	)
	(:init	(character john)
		(character anne)
		(character maggie)
		(character rick)
		(character bob)
		(character matt)
		(character robin)
		(location forest)
		(location vilage)
		(location johnhouse)
		(location neighborhouse)
		(location hospital)
		(location hospitaldoor)
		(location store)
		(location vilageislandbridge)
		(location island)
		(location islandwest)
		(location islandeast)
		(location islandmountainbridge)
		(location mountain)
		(location mountainwest)
		(location mountaineast)
		(item antidote1)
		(item antidote2)
		(item antidote3)
		(item antidote4)
		(item antidote5)
		(item wood1)
		(item wood2)
		(item wood3)
		(item wood4)
		(item hospitalkey)
		(item toolkit1)
		(item toolkit2)
		(item food1)
		(item food2)
		(item food3)
		(item food4)
		(item food5)
		(enemy zombie)
		(bigenemy bigzombie)
		(path johnhouse vilage)
		(path vilage johnhouse)
		(path forest vilage)
		(path vilage forest)
		(path neighborhouse vilage)
		(path vilage neighborhouse)
		(path hospitaldoor vilage)
		(path vilage hospitaldoor)
		(path hospitaldoor hospital)
		(path hospital hospitaldoor)
		(path store vilage)
		(path vilage store)
		(path vilageislandbridge vilage)
		(path vilage vilageislandbridge)
		(path vilageislandbridge island)
		(path island vilageislandbridge)
		(path island islandwest)
		(path islandwest island)
		(path island islandeast)
		(path islandeast island)
		(path island islandmountainbridge)
		(path islandmountainbridge island)
		(path mountain islandmountainbridge)
		(path islandmountainbridge mountain)
		(path mountain mountainwest)
		(path mountainwest mountain)
		(path mountain mountaineast)
		(path mountaineast mountain)
		(open forest)
		(open vilage)
		(open johnhouse)
		(open neighborhouse)
		(open hospital)
		(open store)
		(open island)
		(open islandwest)
		(open islandeast)
		(open mountain)
		(open mountainwest)
		(open mountaineast)
		(safe johnhouse)
		(safe neighborhouse)
		(safe hospital)
		(safe store)
		(hero john)
		(alive john)
		(alive anne)
		(alive maggie)
		(alive rick)
		(alive bob)
		(alive matt)
		(alive robin)
		(healthy john)
		(healthy anne)
		(healthy maggie)
		(healthy rick)
		(healthy bob)
		(healthy matt)
		(healthy robin)
		(at john johnhouse)
		(at anne johnhouse)
		(at maggie johnhouse)
		(at rick store)
		(at bob hospital)
		(at matt islandeast)
		(at robin mountainwest)
		(istool toolkit1)
		(istool toolkit2)
		(iswood wood1)
		(iswood wood2)
		(iswood wood3)
		(iswood wood4)
		(isbridge vilageislandbridge)
		(isbridge islandmountainbridge)
		(isantidote antidote1)
		(isantidote antidote2)
		(isantidote antidote3)
		(isantidote antidote4)
		(isantidote antidote5)
		(isfood food1)
		(isfood food2)
		(isfood food3)
		(isfood food4)
		(isfood food5)
		(iskey hospitalkey hospitaldoor)
		(at food1 mountainwest)
		(at wood1 forest)
		(at hospitalkey forest)
		(at antidote2 hospital)
		(has bob antidote3)
		(has rick food2)
		(at food3 hospital)
		(at wood2 islandeast)
		(at food3 islandmountainbridge)
		(healthy matt)
		(safe neighborhouse)
		(safe islandwest)
		(cured robin)
		(at wood4 islandmountainbridge)
		(safe neighborhouse)
		(healthy robin)
		(cured rick)
		(safe mountain)
		(has rick antidote5)
		(healthy matt)
		(healthy maggie)
		(at wood3 vilageislandbridge)
		(cured maggie)
		(has maggie wood1)
		(fed matt)
		(at antidote5 hospitaldoor)
		(healthy matt)
		(healthy matt)
		(safe islandwest)
		(safe forest)
		(has maggie food1)
		(at food2 neighborhouse)
		(at food1 johnhouse)
		(safe islandmountainbridge)
		(healthy maggie)
		(has rick wood4)
		(cured john)
		(healthy maggie)
		(infected robin)
		(has anne wood2)
		(safe forest)
		(at food4 neighborhouse)
		(fed matt)
		(cured matt)
		(healthy anne)
		(safe mountainwest)
		(has anne antidote1)
		(cured john)
		(safe neighborhouse)
		(fed rick)
		(fed robin)
		(cured matt)
		(fed anne)
		(has john antidote4)
		(has matt antidote3)
		(cured matt)
		(at food5 mountaineast)
		(fed matt)
		(cured rick)
		(safe mountaineast)
		(safe vilage)
		(has anne antidote3)
		(healthy maggie)
		(cured matt)
		(has anne toolkit1)
		(fed bob)
		(healthy matt)
		(at antidote3 neighborhouse)
		(cured maggie)
		(safe islandmountainbridge)
		(safe neighborhouse)
		(at antidote4 johnhouse)
		(safe islandwest)
		(healthy anne)
		(healthy maggie)
		(healthy bob)
		(cured bob)
		(safe vilage)
		(fed anne)
		(cured anne)
		(safe vilage)
		(cured rick)
		(has bob antidote2)
		(safe vilage)
		(healthy maggie)
		(cured maggie)
		(cured bob)
		(safe forest)
		(fed john)
		(fed anne)
		(fed robin)
		(at antidote1 islandmountainbridge)
		(cured matt)
		(fed robin)
		(healthy matt)
		(safe mountaineast)
		(safe island)
		(cured rick)
		(fed john)
		(fed rick)
		(has anne toolkit2)
		(healthy anne)
		(cured rick)
		(fed robin)
		(safe vilageislandbridge)
		(safe store)
		(at maggie islandeast)
		(safe islandmountainbridge)
		(safe vilageislandbridge)
		(fed matt)
		(fed robin)
		(has rick antidote5)
		(healthy bob)
		(healthy maggie)
		(safe hospitaldoor)
		(safe store)
		(fed rick)
		(healthy anne)
		(cured maggie)
		(at toolkit2 forest)
		(healthy bob)
		(cured robin)
		(fed rick)
		(healthy john)
		(fed john)
		(fed matt)
		(safe mountainwest)
		(fed matt)
		(cured bob)
		(cured robin)
		(fed rick)
		(safe island)
		(cured robin)
		(safe store)
		(healthy matt)
		(cured maggie)
		(at robin johnhouse)
		(healthy bob)
		(cured anne)
		(fed anne)
		(cured bob))

	(:goal (and	(at anne islandwest)
		(infected maggie)
		(infected john)
		(at wood2 vilage)
		(cured anne)
		(fed robin)
		(at food3 johnhouse)
		(healthy matt)
		(healthy robin)
		(infected bob)
		(cured rick)
		(has bob antidote4)
		(at antidote3 johnhouse)
		(fed robin)
		(has robin toolkit1)
		(at matt neighborhouse)
		(healthy maggie)
		(at maggie forest)
		(cured maggie)
		(infected anne)
		(cured robin)
		(has john food4)
		(fed bob)
		(cured robin)
		(fed matt)
		(has bob food1)
		(has anne hospitalkey)
		(cured john)
		(at hospitalkey forest)
		(at john store)
		(at rick mountain)
		(fed bob)
		(healthy matt)
		(has rick antidote2)
		(fed anne)
		(at antidote2 hospitaldoor)
		(fed rick)
		(fed john)
		(fed anne)
		(has anne food3)
		(infected bob)
		(cured bob)
		(at bob island)
		(cured robin)
		(cured bob)
		(has john food2)
		(cured robin)
		(healthy matt)
		(fed john)
		(fed bob)
		(cured john)
		(at antidote4 forest)
		(infected matt)
		(at wood1 mountain)
		(fed bob)
		(cured rick)
		(at robin forest)
		(cured maggie)
		(healthy bob)
		(healthy rick)
		(infected anne)
		(at toolkit2 islandmountainbridge)
		(fed robin)
		(infected anne)
		(has anne antidote3)
		(cured matt)
		(at food5 islandeast)
		(at food4 island)
		(cured bob)
		(fed maggie)
		(at antidote5 islandwest)
		(healthy john)
		(fed rick)
		(at wood4 store)
		(cured rick)
		(cured matt)
		(fed maggie)
		(at antidote1 island)
		(fed maggie)
		(fed anne)
		(infected anne)
		(cured robin)
		(fed rick)
		(infected john)
		(cured maggie)
		(fed bob)
		(fed maggie)
		(at maggie hospital)
		(fed john)
		(fed matt)
		(fed maggie)
		(cured bob)
		(at food2 vilageislandbridge)
		(has robin toolkit2)
		(cured anne)
		(fed robin)
		(healthy robin)
		(infected anne)
		(at bob store)
		(has anne antidote5)
		(healthy robin)
		(cured maggie)
		(fed matt)
		(fed maggie)
		(fed rick)
		(at robin hospitaldoor)
		(cured matt)
		(cured maggie)
		(cured john)
		(at bob store)
		(has bob wood3)
		(fed rick))))